### ISSUE TITLE
Eviction of stateful set

### ISSUE THREAD

**Issue by cesartl** [kubernetes-incubator/descheduler#102]
Does the descheduler evict pods created by a `StatefulSet`?

I've got 3 pods from the same the `StatefulSet` in one node but this is not picked up by the duplicate strategy

**Comment by aveshagarwal** [comment]
@cesartl I dont think so, are they using some sort of local storage or anything that might be preventing them from eviction.

**Comment by cesartl** [comment]
There is only a mounted empty dir: 

```yaml
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-sentinel
spec:
  serviceName: redis-sentinel
  replicas: 3
  template:
    metadata:
      labels:
        app: redis-sentinel
      annotations:
        pod.beta.kubernetes.io/init-containers: '[{
            "name": "k8s-redis-ha-sentinel",
            "image": "tarosky/k8s-redis-ha:sentinel-3.0.1",
            "volumeMounts": [{"name": "opt", "mountPath": "/opt"}]
          }]'
    spec:
      containers:
        - name: redis-sentinel
          image: redis:3.2
          command:
            - /opt/bin/k8s-redis-ha-sentinel
          args:
            - /opt/sentinel.conf
          env:
            - name: SERVICE
              value: redis-server
            - name: SERVICE_PORT
              value: redis-server
          ports:
            - containerPort: 26379
              name: redis-sentinel
          readinessProbe:
            exec:
              command: ['redis-cli', '-p', '26379', 'info', 'server']
          volumeMounts:
            - name: opt
              mountPath: /opt
        - name: redis-sword
          image: tarosky/k8s-redis-ha:sword-3.0.1
          env:
            - name: SERVICE
              value: redis-server
            - name: SERVICE_PORT
              value: redis-server
            - name: SENTINEL
              value: redis-sentinel
            - name: SENTINEL_PORT
              value: redis-sentinel
          volumeMounts:
            - name: opt
              mountPath: /opt
      volumes:
        - name: opt
          emptyDir: {}
```
