### ISSUE TITLE
No documentation on how to rerun the Job

### ISSUE THREAD

**Issue by desourav** [kubernetes-incubator/descheduler#176]
I have the kubernetes Job deployed :  
```
$ kubectl get job -n kube-system
NAME              COMPLETIONS   DURATION   AGE
descheduler-job   1/1           3s         78m
```
The Job ran the pod to completion : 
```
$ kubectl get po -n kube-system | grep descheduler
descheduler-job-ltcp8                                 0/1     Completed           0          78m
```
Two questions : 
1. How to rerun the job? 
2. Does descheduler run by itself in the background whenever any of the rules in the configmap is violated?
```
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "RemoveDuplicates":
     enabled: true
  "RemovePodsViolatingInterPodAntiAffinity":
     enabled: true
```
