### ISSUE TITLE
Add support for node affinity strategy

### ISSUE THREAD

**Issue by containscafeine** [kubernetes-incubator/descheduler#46]
From the little that I read about node affinity, does adding the following strategy make sense -

For pods with node affinity set using `preferredDuringSchedulingIgnoredDuringExecution`, it might be possible that the preferred node was unavailable during scheduling and the pod was scheduled on another node. In this case, if the descheduler is run, it does the following -

1. checks for all the pods with nodeAffinity defined using `preferredDuringSchedulingIgnoredDuringExecution`
2. checks if the pod is actually scheduled on the preferred node or not
3. if not, descheduler checks if the preferred node is available and is schedulable
4. if such a node is found, descheduler evicts the pod (and hopefully the scheduler schedules it on the preferred node :tada:)

Maybe we could have a policy file describing the strategy like -

```yaml
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "RemovePodsViolatingNodeAffinity":
     enabled: true
```

@aveshagarwal @ravisantoshgudimetla if this makes sense, can I take a stab at a PoC for this?
