### ISSUE TITLE
Add support for inter-pod affinity strategy

### ISSUE THREAD

**Issue by containscafeine** [kubernetes-incubator/descheduler#47]
For pods with `podAffinity` set using `preferredDuringSchedulingIgnoredDuringExecution`, it might be possible that at the time of scheduling on the current node, no pod with the set labels were running, but still the pod got scheduled on the current node since the nature of the affinity was _preferred_ and not _required_.

In such a case, if the descheduler is run, it can do the following -
1. finds pods running with `podAffinity` set using `preferredDuringSchedulingIgnoredDuringExecution`
2. checks if the pods found in 1 are scheduled on the desired node or not
3. if not, descheduler checks on other schedulable nodes if the desired pods are running where this `podAffinity` condition can be met
4. if such a node is found, descheduler evicts the pod (and hopefully the scheduler schedules it on the desired node :tada:)

Maybe we could have a policy file describing the strategy like -

```yaml
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "RemovePodsViolatingPodAffinity":
     enabled: true
```

Does it make sense to support such a strategy?
