### ISSUE TITLE
confusing with "RemovePodsViolatingInterPodAntiAffinity" strategy

### ISSUE THREAD

**Issue by wjiangjay** [kubernetes-incubator/descheduler#77]
hi:

Just want to make it work and I found that this strategy is not work as my expect.

> descheduler version 
Descheduler version {Major:0 Minor:4+ GitCommit:d3c2f256852874fdca4682c3c94bc30624979036 GitVersion:v0.4.0 BuildDate:2018-01-10T13:23:09+0800 GoVersion:go1.8.5 Compiler:gc Platform:linux/amd64}

The origin try is as the following steps:
1. keep only one node schedulable 
2. create a rc
oc run hello --image=openshift/hello-openshift:latest
3. Create another rc with antiaffinity

```
affinity:
   podAntiAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
     - labelSelector:
         matchExpressions:
         - key: key
           operator: In
           values: [“value”]
       topologyKey: kubernetes.io/hostname
```

4. wait all pods of rc is running;
5.  label the pod of first rc with 
oc label pod <pod_name>  key=value
6. Setup descheduler and try to evicted pods

Then I found no one pod has been evicted.

Then I go through all the unit test and try to catch a demo for this strategy.
And try to reproduce the test in https://github.com/kubernetes-incubator/descheduler/blob/master/pkg/descheduler/strategies/pod_antiaffinity_test.go

Then the reproduced steps is:

The origin try is as the following steps:
1. keep only one node schedulable 
2. Create a rc with antiaffinity

```
affinity:
   podAntiAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
     - labelSelector:
         matchExpressions:
         - key: key
           operator: In
           values: [“value”]
       topologyKey: kubernetes.io/hostname
```

3. Create a rc with the some antiaffinity as step 2
4. wait all pods of rc is running;
5.  label the pod of first rc with 
oc label pod <pod_name>  key=value
6. Setup descheduler and try to evicted pods

Then I found there is one pod has been evicted.

So here I want to discuss is if only one scenario(in the unit test) is for the strategy.
And why my origin steps can not work? Is it a bug?

Thanks!

**Comment by ravisantoshgudimetla** [comment]
@wjiangjay Are you still seeing the issue? If yes, can you increase debug level and provide logs?

**Comment by afoninsky** [comment]
I'm confused too. Either I did not understand core concept, or I failed with configs.

I expect pods will be rescheduled with following configuration rules, but they are not:

```
❯ kubectl -n fulldive-staging get pod -l app=fulldive-api -o wide                                                         kubernetes/git/NAME                          READY     STATUS    RESTARTS   AGE       IP          NODE
fulldive-api-c97f775c-lgtrl   2/2       Running   0          2h        10.48.8.7   gke-staging-default-pool-1ec08eb0-7xkq
fulldive-api-c97f775c-nwrcj   2/2       Running   0          2h        10.48.8.5   gke-staging-default-pool-1ec08eb0-7xkq
fulldive-api-c97f775c-z6z6n   2/2       Running   0          2h        10.48.8.6   gke-staging-default-pool-1ec08eb0-7xkq
```

```
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: fulldive-api
```

```
    apiVersion: descheduler/v1alpha1
    kind: DeschedulerPolicy
    strategies:
      RemovePodsViolatingInterPodAntiAffinity:
        enabled: true
```
